-- Create Database and Schemas
CREATE OR REPLACE DATABASE REDBUS_ANALYTICS;

CREATE OR REPLACE SCHEMA REDBUS_ANALYTICS.RAW;

CREATE OR REPLACE SCHEMA REDBUS_ANALYTICS.DW;

CREATE OR REPLACE SCHEMA REDBUS_ANALYTICS.SEMANTIC;


CREATE OR REPLACE TABLE REDBUS_ANALYTICS.RAW.RAW_CUSTOMERS (
    CUSTOMER_ID VARCHAR(50),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(200),
    PHONE VARCHAR(50),
    SEGMENT VARCHAR(50),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTRY VARCHAR(100),
    UPDATED_AT TIMESTAMP_NTZ  -- Added this column
);

-- Create RAW_ROUTES (EXACT columns from CSV)
CREATE TABLE REDBUS_ANALYTICS.RAW.RAW_ROUTES (
    ROUTE_ID VARCHAR(50),
    SOURCE_CITY VARCHAR(100),
    DEST_CITY VARCHAR(100),
    DISTANCE_KM NUMBER(10,2),
    SOURCE_STATE VARCHAR(10),
    DEST_STATE VARCHAR(10),
    REGION VARCHAR(100),
    EFFECTIVE_FROM TIMESTAMP_NTZ, 
    STATUS VARCHAR(30)
);

-- Create RAW_BUSES (EXACT columns from CSV)
CREATE TABLE REDBUS_ANALYTICS.RAW.RAW_BUSES (
    BUS_ID VARCHAR(50),
    OPERATOR_NAME VARCHAR(200),
    BUS_TYPE VARCHAR(50),
    SEAT_CAPACITY NUMBER(5),
    BUS_MODEL VARCHAR(50),
    REGISTRATION_NO VARCHAR(50),
    IN_SERVICE_DATE DATE,
    STATUS VARCHAR(20),
    UPDATED_AT TIMESTAMP_NTZ
);

-- Create RAW_BOOKINGS (EXACT columns from CSV)
CREATE TABLE REDBUS_ANALYTICS.RAW.RAW_BOOKINGS (
    BOOKING_ID VARCHAR(50),
    BOOKING_LINE_ID VARCHAR(50),
    BOOKING_DATE DATE,
    CUSTOMER_ID VARCHAR(50),
    ROUTE_ID VARCHAR(50),
    BUS_ID VARCHAR(50),
    JOURNEY_DATE DATE,
    DEPARTURE_TIME TIME,
    ARRIVAL_TIME TIME,
    SEAT_TYPE VARCHAR(50),
    SEAT_NO VARCHAR(10),
    PASSENGER_COUNT NUMBER(5),
    FARE_AMOUNT NUMBER(10,2),
    DISCOUNT_PCT NUMBER(5,2),
    PAYMENT_MODE VARCHAR(50),
    BOOKING_STATUS VARCHAR(20)
);


-- upto here the loading the csv as a table is completed now we have the in the data base we have the DW schema so we gonna build star schema next 

-- we have created the DIMENSION tables like customer , route , date , bus 

CREATE OR REPLACE TABLE REDBUS_ANALYTICS.DW.DIM_DATE (
    DATE_KEY NUMBER(8) PRIMARY KEY,
    FULL_DATE DATE,
    YEAR NUMBER(4),
    QUARTER NUMBER(1),
    MONTH NUMBER(2),
    MONTH_NAME VARCHAR(20),
    DAY NUMBER(2),
    DAY_NAME VARCHAR(20),
    DAY_OF_WEEK NUMBER(1),
    WEEK_OF_YEAR NUMBER(2),
    IS_WEEKEND BOOLEAN
);


INSERT INTO REDBUS_ANALYTICS.DW.DIM_DATE (DATE_KEY, FULL_DATE, YEAR, QUARTER, MONTH, MONTH_NAME, DAY, DAY_NAME, DAY_OF_WEEK, WEEK_OF_YEAR, IS_WEEKEND)
SELECT 
    TO_NUMBER(TO_CHAR(DATEADD(DAY, SEQ4(), '2023-01-01'), 'YYYYMMDD')) AS DATE_KEY,
    DATEADD(DAY, SEQ4(), '2023-01-01') AS FULL_DATE,
    YEAR(DATEADD(DAY, SEQ4(), '2023-01-01')) AS YEAR,
    QUARTER(DATEADD(DAY, SEQ4(), '2023-01-01')) AS QUARTER,
    MONTH(DATEADD(DAY, SEQ4(), '2023-01-01')) AS MONTH,
    TO_CHAR(DATEADD(DAY, SEQ4(), '2023-01-01'), 'MMMM') AS MONTH_NAME,
    DAY(DATEADD(DAY, SEQ4(), '2023-01-01')) AS DAY,
    TO_CHAR(DATEADD(DAY, SEQ4(), '2023-01-01'), 'DAY') AS DAY_NAME,
    DAYOFWEEK(DATEADD(DAY, SEQ4(), '2023-01-01')) AS DAY_OF_WEEK,
    WEEKOFYEAR(DATEADD(DAY, SEQ4(), '2023-01-01')) AS WEEK_OF_YEAR,
    CASE WHEN DAYOFWEEK(DATEADD(DAY, SEQ4(), '2023-01-01')) IN (6, 7) THEN TRUE ELSE FALSE END AS IS_WEEKEND
FROM TABLE(GENERATOR(ROWCOUNT => 1096));


SELECT COUNT(*) FROM REDBUS_ANALYTICS.DW.DIM_DATE;

SELECT * FROM REDBUS_ANALYTICS.DW.DIM_DATE LIMIT 10;

CREATE OR REPLACE TABLE REDBUS_ANALYTICS.DW.DIM_CUSTOMER (
    CUSTOMER_SK NUMBER(10) IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(50),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(200),
    PHONE VARCHAR(50),
    SEGMENT VARCHAR(50),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTRY VARCHAR(100),
    EFFECTIVE_START_TS TIMESTAMP_NTZ,
    EFFECTIVE_END_TS TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN
);


INSERT INTO REDBUS_ANALYTICS.DW.DIM_CUSTOMER (
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE,
    SEGMENT,
    CITY,
    STATE,
    COUNTRY,
    EFFECTIVE_START_TS,
    EFFECTIVE_END_TS,
    IS_CURRENT
)
SELECT 
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE,
    SEGMENT,
    CITY,
    STATE,
    COUNTRY,
    CURRENT_TIMESTAMP() AS EFFECTIVE_START_TS,
    '9999-12-31' AS EFFECTIVE_END_TS,
    TRUE AS IS_CURRENT
FROM REDBUS_ANALYTICS.RAW.RAW_CUSTOMERS;


CREATE OR REPLACE TABLE REDBUS_ANALYTICS.DW.DIM_ROUTE (
    ROUTE_SK NUMBER(10) IDENTITY(1,1) PRIMARY KEY,
    ROUTE_ID VARCHAR(50),
    SOURCE_CITY VARCHAR(100),
    DEST_CITY VARCHAR(100),
    DISTANCE_KM NUMBER(10,2),
    SOURCE_STATE VARCHAR(10),
    DEST_STATE VARCHAR(10),
    REGION VARCHAR(100)
);


INSERT INTO REDBUS_ANALYTICS.DW.DIM_ROUTE (
    ROUTE_ID,
    SOURCE_CITY,
    DEST_CITY,
    DISTANCE_KM,
    SOURCE_STATE,
    DEST_STATE,
    REGION
)
SELECT 
    ROUTE_ID,
    SOURCE_CITY,
    DEST_CITY,
    DISTANCE_KM,
    SOURCE_STATE,
    DEST_STATE,
    REGION
FROM REDBUS_ANALYTICS.RAW.RAW_ROUTES;

CREATE OR REPLACE TABLE REDBUS_ANALYTICS.DW.DIM_BUS (
    BUS_SK NUMBER(10) IDENTITY(1,1) PRIMARY KEY,
    BUS_ID VARCHAR(50),
    OPERATOR_NAME VARCHAR(200),
    BUS_TYPE VARCHAR(50),
    SEAT_CAPACITY NUMBER(5),
    BUS_MODEL VARCHAR(50),
    REGISTRATION_NO VARCHAR(50),
    IN_SERVICE_DATE DATE,
    STATUS VARCHAR(20),
    EFFECTIVE_START_TS TIMESTAMP_NTZ,
    EFFECTIVE_END_TS TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN
);

INSERT INTO REDBUS_ANALYTICS.DW.DIM_BUS (
    BUS_ID,
    OPERATOR_NAME,
    BUS_TYPE,
    SEAT_CAPACITY,
    BUS_MODEL,
    REGISTRATION_NO,
    IN_SERVICE_DATE,
    STATUS,
    EFFECTIVE_START_TS,
    EFFECTIVE_END_TS,
    IS_CURRENT
)
SELECT 
    BUS_ID,
    OPERATOR_NAME,
    BUS_TYPE,
    SEAT_CAPACITY,
    BUS_MODEL,
    REGISTRATION_NO,
    IN_SERVICE_DATE,
    STATUS,
    CURRENT_TIMESTAMP() AS EFFECTIVE_START_TS,
    '9999-12-31' AS EFFECTIVE_END_TS,
    TRUE AS IS_CURRENT
FROM REDBUS_ANALYTICS.RAW.RAW_BUSES;

-- untill this we have created the dimention table 

-- we are gonna create the fact table  which is gonna only one table is fact_booking

CREATE OR REPLACE TABLE REDBUS_ANALYTICS.DW.FACT_BOOKING (
    -- Surrogate Key
    BOOKING_SK NUMBER(10) IDENTITY(1,1) PRIMARY KEY,
    
    -- Business Keys (for traceability)
    BOOKING_ID VARCHAR(50),
    BOOKING_LINE_ID VARCHAR(50),
    
    -- Foreign Keys to Dimensions
    BOOKING_DATE_KEY NUMBER(8) REFERENCES REDBUS_ANALYTICS.DW.DIM_DATE(DATE_KEY),
    JOURNEY_DATE_KEY NUMBER(8) REFERENCES REDBUS_ANALYTICS.DW.DIM_DATE(DATE_KEY),
    CUSTOMER_SK NUMBER(10) REFERENCES REDBUS_ANALYTICS.DW.DIM_CUSTOMER(CUSTOMER_SK),
    ROUTE_SK NUMBER(10) REFERENCES REDBUS_ANALYTICS.DW.DIM_ROUTE(ROUTE_SK),
    BUS_SK NUMBER(10) REFERENCES REDBUS_ANALYTICS.DW.DIM_BUS(BUS_SK),
    
    -- Facts (Measurements)
    PASSENGER_COUNT NUMBER(5),
    FARE_AMOUNT NUMBER(10,2),
    DISCOUNT_PCT NUMBER(5,2),
    NET_AMOUNT NUMBER(10,2),  -- Calculated: FARE_AMOUNT * (1 - DISCOUNT_PCT/100)
    
    -- Attributes
    SEAT_TYPE VARCHAR(50),
    SEAT_NO VARCHAR(10),
    PAYMENT_MODE VARCHAR(50),
    BOOKING_STATUS VARCHAR(20),
    
    -- Audit Columns
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO REDBUS_ANALYTICS.DW.FACT_BOOKING (
    BOOKING_ID,
    BOOKING_LINE_ID,
    BOOKING_DATE_KEY,
    JOURNEY_DATE_KEY,
    CUSTOMER_SK,
    ROUTE_SK,
    BUS_SK,
    PASSENGER_COUNT,
    FARE_AMOUNT,
    DISCOUNT_PCT,
    NET_AMOUNT,
    SEAT_TYPE,
    SEAT_NO,
    PAYMENT_MODE,
    BOOKING_STATUS,
    LOAD_TS
)
SELECT 
    b.BOOKING_ID,
    b.BOOKING_LINE_ID,
    d1.DATE_KEY AS BOOKING_DATE_KEY,
    d2.DATE_KEY AS JOURNEY_DATE_KEY,
    c.CUSTOMER_SK,
    r.ROUTE_SK,
    bu.BUS_SK,
    b.PASSENGER_COUNT,
    b.FARE_AMOUNT,
    b.DISCOUNT_PCT,
    b.FARE_AMOUNT * (1 - b.DISCOUNT_PCT / 100) AS NET_AMOUNT,
    b.SEAT_TYPE,
    b.SEAT_NO,
    b.PAYMENT_MODE,
    b.BOOKING_STATUS,
    CURRENT_TIMESTAMP() AS LOAD_TS
FROM REDBUS_ANALYTICS.RAW.RAW_BOOKINGS b
LEFT JOIN REDBUS_ANALYTICS.DW.DIM_DATE d1 
    ON b.BOOKING_DATE = d1.FULL_DATE
LEFT JOIN REDBUS_ANALYTICS.DW.DIM_DATE d2 
    ON b.JOURNEY_DATE = d2.FULL_DATE
LEFT JOIN REDBUS_ANALYTICS.DW.DIM_CUSTOMER c 
    ON b.CUSTOMER_ID = c.CUSTOMER_ID AND c.IS_CURRENT = TRUE
LEFT JOIN REDBUS_ANALYTICS.DW.DIM_ROUTE r 
    ON b.ROUTE_ID = r.ROUTE_ID
LEFT JOIN REDBUS_ANALYTICS.DW.DIM_BUS bu 
    ON b.BUS_ID = bu.BUS_ID AND bu.IS_CURRENT = TRUE;

-- Check row count
SELECT COUNT(*) FROM REDBUS_ANALYTICS.DW.FACT_BOOKING;

-- Preview the data
SELECT * FROM REDBUS_ANALYTICS.DW.FACT_BOOKING LIMIT 10;

-- Check for any NULL foreign keys (should be 0)
SELECT 
    SUM(CASE WHEN BOOKING_DATE_KEY IS NULL THEN 1 ELSE 0 END) AS NULL_BOOKING_DATE,
    SUM(CASE WHEN JOURNEY_DATE_KEY IS NULL THEN 1 ELSE 0 END) AS NULL_JOURNEY_DATE,
    SUM(CASE WHEN CUSTOMER_SK IS NULL THEN 1 ELSE 0 END) AS NULL_CUSTOMER,
    SUM(CASE WHEN ROUTE_SK IS NULL THEN 1 ELSE 0 END) AS NULL_ROUTE,
    SUM(CASE WHEN BUS_SK IS NULL THEN 1 ELSE 0 END) AS NULL_BUS
FROM REDBUS_ANALYTICS.DW.FACT_BOOKING;

SELECT DISTINCT BOOKING_DATE FROM REDBUS_ANALYTICS.RAW.RAW_BOOKINGS;

SELECT DISTINCT FULL_DATE 
FROM REDBUS_ANALYTICS.DW.DIM_DATE 
WHERE FULL_DATE IN (SELECT DISTINCT BOOKING_DATE FROM REDBUS_ANALYTICS.RAW.RAW_BOOKINGS);


INSERT INTO REDBUS_ANALYTICS.DW.DIM_DATE (DATE_KEY, FULL_DATE, YEAR, QUARTER, MONTH, MONTH_NAME, DAY, DAY_NAME, DAY_OF_WEEK, WEEK_OF_YEAR, IS_WEEKEND)
SELECT 
    TO_NUMBER(TO_CHAR(DATEADD(DAY, SEQ4(), '2020-01-01'), 'YYYYMMDD')) AS DATE_KEY,
    DATEADD(DAY, SEQ4(), '2020-01-01') AS FULL_DATE,
    YEAR(DATEADD(DAY, SEQ4(), '2020-01-01')) AS YEAR,
    QUARTER(DATEADD(DAY, SEQ4(), '2020-01-01')) AS QUARTER,
    MONTH(DATEADD(DAY, SEQ4(), '2020-01-01')) AS MONTH,
    TO_CHAR(DATEADD(DAY, SEQ4(), '2020-01-01'), 'MMMM') AS MONTH_NAME,
    DAY(DATEADD(DAY, SEQ4(), '2020-01-01')) AS DAY,
    TO_CHAR(DATEADD(DAY, SEQ4(), '2020-01-01'), 'DAY') AS DAY_NAME,
    DAYOFWEEK(DATEADD(DAY, SEQ4(), '2020-01-01')) AS DAY_OF_WEEK,
    WEEKOFYEAR(DATEADD(DAY, SEQ4(), '2020-01-01')) AS WEEK_OF_YEAR,
    CASE WHEN DAYOFWEEK(DATEADD(DAY, SEQ4(), '2020-01-01')) IN (6, 7) THEN TRUE ELSE FALSE END AS IS_WEEKEND
FROM TABLE(GENERATOR(ROWCOUNT => 2557));


SELECT 
    BOOKING_ID,
    BOOKING_DATE_KEY,
    JOURNEY_DATE_KEY,
    CUSTOMER_SK,
    ROUTE_SK,
    BUS_SK,
    NET_AMOUNT
FROM REDBUS_ANALYTICS.DW.FACT_BOOKING 
LIMIT 10;


-- end of fact table 
-- until here the star schema is completed and created 

-- validation check
SELECT COUNT(*) FROM REDBUS_ANALYTICS.DW.FACT_BOOKING;

-- checking the null and there is no null values
SELECT 
    SUM(CASE WHEN BOOKING_DATE_KEY IS NULL THEN 1 ELSE 0 END) AS NULL_BOOKING_DATE,
    SUM(CASE WHEN JOURNEY_DATE_KEY IS NULL THEN 1 ELSE 0 END) AS NULL_JOURNEY_DATE,
    SUM(CASE WHEN CUSTOMER_SK IS NULL THEN 1 ELSE 0 END) AS NULL_CUSTOMER,
    SUM(CASE WHEN ROUTE_SK IS NULL THEN 1 ELSE 0 END) AS NULL_ROUTE,
    SUM(CASE WHEN BUS_SK IS NULL THEN 1 ELSE 0 END) AS NULL_BUS
FROM REDBUS_ANALYTICS.DW.FACT_BOOKING;


-- view example of complete data 
SELECT 
    b.BOOKING_ID,
    d1.FULL_DATE AS BOOKING_DATE,
    d2.FULL_DATE AS JOURNEY_DATE,
    c.FIRST_NAME || ' ' || c.LAST_NAME AS CUSTOMER_NAME,
    r.SOURCE_CITY || ' → ' || r.DEST_CITY AS ROUTE,
    bu.OPERATOR_NAME || ' - ' || bu.BUS_TYPE AS BUS,
    b.NET_AMOUNT
FROM REDBUS_ANALYTICS.DW.FACT_BOOKING b
LEFT JOIN REDBUS_ANALYTICS.DW.DIM_DATE d1 ON b.BOOKING_DATE_KEY = d1.DATE_KEY
LEFT JOIN REDBUS_ANALYTICS.DW.DIM_DATE d2 ON b.JOURNEY_DATE_KEY = d2.DATE_KEY
LEFT JOIN REDBUS_ANALYTICS.DW.DIM_CUSTOMER c ON b.CUSTOMER_SK = c.CUSTOMER_SK
LEFT JOIN REDBUS_ANALYTICS.DW.DIM_ROUTE r ON b.ROUTE_SK = r.ROUTE_SK
LEFT JOIN REDBUS_ANALYTICS.DW.DIM_BUS bu ON b.BUS_SK = bu.BUS_SK
LIMIT 10;

-- validation end everything looks normal

-- Create Semantic Views

CREATE OR REPLACE VIEW REDBUS_ANALYTICS.SEMANTIC.VW_CUSTOMER AS
SELECT 
    CUSTOMER_SK,
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULL_NAME,
    EMAIL,
    PHONE,
    SEGMENT,
    CITY,
    STATE,
    COUNTRY,
    CASE 
        WHEN SEGMENT = 'PREMIUM' THEN 'High Value'
        WHEN SEGMENT = 'VIP' THEN 'Frequent Traveler'
        WHEN SEGMENT = 'REGULAR' THEN 'Standard'
        ELSE 'Unknown'
    END AS SEGMENT_DESCRIPTION,
    IS_CURRENT
FROM REDBUS_ANALYTICS.DW.DIM_CUSTOMER
WHERE IS_CURRENT = TRUE;

CREATE OR REPLACE VIEW REDBUS_ANALYTICS.SEMANTIC.VW_BUS AS
SELECT 
    BUS_SK,
    BUS_ID,
    OPERATOR_NAME,
    BUS_TYPE,
    SEAT_CAPACITY,
    BUS_MODEL,
    REGISTRATION_NO,
    IN_SERVICE_DATE,
    STATUS,
    CASE 
        WHEN SEAT_CAPACITY > 40 THEN 'Large Bus'
        WHEN SEAT_CAPACITY > 30 THEN 'Medium Bus'
        WHEN SEAT_CAPACITY > 20 THEN 'Small Bus'
        ELSE 'Mini Bus'
    END AS BUS_SIZE_CATEGORY,
    IS_CURRENT
FROM REDBUS_ANALYTICS.DW.DIM_BUS
WHERE IS_CURRENT = TRUE;

CREATE OR REPLACE VIEW REDBUS_ANALYTICS.SEMANTIC.VW_ROUTE AS
SELECT 
    ROUTE_SK,
    ROUTE_ID,
    SOURCE_CITY,
    DEST_CITY,
    CONCAT(SOURCE_CITY, ' → ', DEST_CITY) AS ROUTE_DESCRIPTION,
    DISTANCE_KM,
    SOURCE_STATE,
    DEST_STATE,
    REGION,
    CASE 
        WHEN DISTANCE_KM > 800 THEN 'Long Distance'
        WHEN DISTANCE_KM > 400 THEN 'Medium Distance'
        ELSE 'Short Distance'
    END AS DISTANCE_CATEGORY
FROM REDBUS_ANALYTICS.DW.DIM_ROUTE;

CREATE OR REPLACE VIEW REDBUS_ANALYTICS.SEMANTIC.VW_DATE AS
SELECT 
    DATE_KEY,
    FULL_DATE,
    YEAR,
    QUARTER,
    MONTH,
    MONTH_NAME,
    DAY,
    DAY_NAME,
    DAY_OF_WEEK,
    WEEK_OF_YEAR,
    IS_WEEKEND,
    CASE 
        WHEN IS_WEEKEND = TRUE THEN 'Weekend'
        ELSE 'Weekday'
    END AS DAY_TYPE,
    CASE 
        WHEN MONTH >= 4 THEN YEAR
        ELSE YEAR - 1
    END AS FISCAL_YEAR,
    CASE 
        WHEN MONTH BETWEEN 4 AND 6 THEN 'Q1'
        WHEN MONTH BETWEEN 7 AND 9 THEN 'Q2'
        WHEN MONTH BETWEEN 10 AND 12 THEN 'Q3'
        ELSE 'Q4'
    END AS FISCAL_QUARTER
FROM REDBUS_ANALYTICS.DW.DIM_DATE;

CREATE OR REPLACE VIEW REDBUS_ANALYTICS.SEMANTIC.VW_BOOKINGS AS
SELECT 
    -- Booking Details
    b.BOOKING_ID,
    b.BOOKING_LINE_ID,
    b.SEAT_TYPE,
    b.SEAT_NO,
    b.PAYMENT_MODE,
    b.BOOKING_STATUS,
    b.PASSENGER_COUNT,
    b.FARE_AMOUNT,
    b.DISCOUNT_PCT,
    b.NET_AMOUNT,
    
    -- Booking Date
    b.BOOKING_DATE_KEY,
    bd.FULL_DATE AS BOOKING_DATE,
    bd.YEAR AS BOOKING_YEAR,
    bd.MONTH_NAME AS BOOKING_MONTH,
    bd.QUARTER AS BOOKING_QUARTER,
    bd.DAY_NAME AS BOOKING_DAY,
    bd.IS_WEEKEND AS BOOKING_IS_WEEKEND,
    
    -- Journey Date
    b.JOURNEY_DATE_KEY,
    jd.FULL_DATE AS JOURNEY_DATE,
    jd.YEAR AS JOURNEY_YEAR,
    jd.MONTH_NAME AS JOURNEY_MONTH,
    jd.QUARTER AS JOURNEY_QUARTER,
    jd.DAY_NAME AS JOURNEY_DAY,
    jd.IS_WEEKEND AS JOURNEY_IS_WEEKEND,
    
    -- Customer Details
    b.CUSTOMER_SK,
    c.CUSTOMER_ID,
    c.FULL_NAME AS CUSTOMER_NAME,
    c.SEGMENT AS CUSTOMER_SEGMENT,
    c.CITY AS CUSTOMER_CITY,
    c.STATE AS CUSTOMER_STATE,
    c.COUNTRY AS CUSTOMER_COUNTRY,
    c.SEGMENT_DESCRIPTION,
    
    -- Route Details
    b.ROUTE_SK,
    r.ROUTE_ID,
    r.SOURCE_CITY,
    r.DEST_CITY,
    r.ROUTE_DESCRIPTION,
    r.DISTANCE_KM,
    r.REGION,
    r.DISTANCE_CATEGORY,
    
    -- Bus Details
    b.BUS_SK,
    bu.BUS_ID,
    bu.OPERATOR_NAME,
    bu.BUS_TYPE,
    bu.SEAT_CAPACITY,
    bu.BUS_SIZE_CATEGORY,
    bu.BUS_MODEL,
    bu.STATUS AS BUS_STATUS,
    
    -- Calculated Metrics
    b.FARE_AMOUNT / NULLIF(b.PASSENGER_COUNT, 0) AS FARE_PER_PASSENGER,
    b.NET_AMOUNT / NULLIF(b.PASSENGER_COUNT, 0) AS NET_PER_PASSENGER,
    CASE 
        WHEN b.BOOKING_STATUS = 'CANCELLED' THEN TRUE 
        ELSE FALSE 
    END AS IS_CANCELLED,
    CASE 
        WHEN b.BOOKING_STATUS = 'CANCELLED' THEN b.NET_AMOUNT 
        ELSE 0 
    END AS CANCELLED_REVENUE,
    CASE 
        WHEN b.BOOKING_STATUS != 'CANCELLED' THEN b.NET_AMOUNT 
        ELSE 0 
    END AS CONFIRMED_REVENUE
    
FROM REDBUS_ANALYTICS.DW.FACT_BOOKING b
LEFT JOIN REDBUS_ANALYTICS.SEMANTIC.VW_DATE bd 
    ON b.BOOKING_DATE_KEY = bd.DATE_KEY
LEFT JOIN REDBUS_ANALYTICS.SEMANTIC.VW_DATE jd 
    ON b.JOURNEY_DATE_KEY = jd.DATE_KEY
LEFT JOIN REDBUS_ANALYTICS.SEMANTIC.VW_CUSTOMER c 
    ON b.CUSTOMER_SK = c.CUSTOMER_SK
LEFT JOIN REDBUS_ANALYTICS.SEMANTIC.VW_ROUTE r 
    ON b.ROUTE_SK = r.ROUTE_SK
LEFT JOIN REDBUS_ANALYTICS.SEMANTIC.VW_BUS bu 
    ON b.BUS_SK = bu.BUS_SK;

-- until now the view are created over we have deployed all the tables into the views that VW , why we did this because insted writing complex queries we can use the view that make the operation simple 

-- Run Some Business Queries!

-- 1 , total revenue by month
SELECT 
    JOURNEY_YEAR,
    JOURNEY_MONTH,
    SUM(NET_AMOUNT) AS TOTAL_REVENUE
FROM REDBUS_ANALYTICS.SEMANTIC.VW_BOOKINGS
GROUP BY JOURNEY_YEAR, JOURNEY_MONTH
ORDER BY JOURNEY_YEAR, JOURNEY_MONTH;

--2,  Top 5 Routes by Revenue:
SELECT 
    ROUTE_DESCRIPTION,
    COUNT(*) AS NUMBER_OF_BOOKINGS,
    SUM(NET_AMOUNT) AS TOTAL_REVENUE
FROM REDBUS_ANALYTICS.SEMANTIC.VW_BOOKINGS
WHERE BOOKING_STATUS != 'CANCELLED'
GROUP BY ROUTE_DESCRIPTION
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;

-- 3 , Cancellation Rate:
SELECT 
    JOURNEY_MONTH,
    COUNT(*) AS TOTAL_BOOKINGS,
    SUM(CASE WHEN IS_CANCELLED = TRUE THEN 1 ELSE 0 END) AS CANCELLED_BOOKINGS,
    (SUM(CASE WHEN IS_CANCELLED = TRUE THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS CANCELLATION_RATE
FROM REDBUS_ANALYTICS.SEMANTIC.VW_BOOKINGS
GROUP BY JOURNEY_MONTH
ORDER BY JOURNEY_MONTH;

-- 4, Top Operators by Revenue:
SELECT 
    OPERATOR_NAME,
    COUNT(*) AS TRIPS,
    SUM(NET_AMOUNT) AS TOTAL_REVENUE
FROM REDBUS_ANALYTICS.SEMANTIC.VW_BOOKINGS
WHERE BOOKING_STATUS != 'CANCELLED'
GROUP BY OPERATOR_NAME
ORDER BY TOTAL_REVENUE DESC;


-- 5, Executive Dashboard - Daily Summary
SELECT 
    JOURNEY_DATE,
    COUNT(DISTINCT BOOKING_ID) AS TOTAL_BOOKINGS,
    SUM(PASSENGER_COUNT) AS TOTAL_PASSENGERS,
    SUM(NET_AMOUNT) AS TOTAL_REVENUE,
    AVG(NET_AMOUNT) AS AVG_TICKET_VALUE,
    SUM(CASE WHEN IS_CANCELLED = TRUE THEN 1 ELSE 0 END) AS CANCELLED_BOOKINGS,
    ROUND(SUM(CASE WHEN IS_CANCELLED = TRUE THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS CANCELLATION_RATE
FROM REDBUS_ANALYTICS.SEMANTIC.VW_BOOKINGS
GROUP BY JOURNEY_DATE
ORDER BY JOURNEY_DATE DESC;

-- 6 ,Monthly Revenue Trend
SELECT 
    JOURNEY_YEAR,
    JOURNEY_MONTH,
    COUNT(DISTINCT BOOKING_ID) AS BOOKINGS,
    SUM(PASSENGER_COUNT) AS PASSENGERS,
    SUM(NET_AMOUNT) AS REVENUE,
    AVG(NET_AMOUNT) AS AVG_REVENUE_PER_BOOKING,
    SUM(CASE WHEN IS_CANCELLED = TRUE THEN 1 ELSE 0 END) AS CANCELLATIONS,
    ROUND(SUM(CASE WHEN IS_CANCELLED = TRUE THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS CANCEL_RATE
FROM REDBUS_ANALYTICS.SEMANTIC.VW_BOOKINGS
GROUP BY JOURNEY_YEAR, JOURNEY_MONTH
ORDER BY JOURNEY_YEAR, JOURNEY_MONTH;

-- 7, Operator Performance Analysis

SELECT 
    OPERATOR_NAME,
    COUNT(DISTINCT BOOKING_ID) AS BOOKINGS,
    SUM(PASSENGER_COUNT) AS PASSENGERS,
    SUM(NET_AMOUNT) AS REVENUE,
    AVG(NET_AMOUNT / PASSENGER_COUNT) AS AVG_FARE_PER_PASSENGER,
    ROUND(SUM(CASE WHEN IS_CANCELLED = TRUE THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS CANCEL_RATE
FROM REDBUS_ANALYTICS.SEMANTIC.VW_BOOKINGS
GROUP BY OPERATOR_NAME
ORDER BY REVENUE DESC;

-- 8,  Bus Type Performance
SELECT 
    BUS_TYPE,
    COUNT(DISTINCT BOOKING_ID) AS BOOKINGS,
    SUM(PASSENGER_COUNT) AS PASSENGERS,
    SUM(NET_AMOUNT) AS REVENUE,
    AVG(SEAT_CAPACITY) AS AVG_CAPACITY,
    ROUND(SUM(PASSENGER_COUNT) * 100.0 / SUM(SEAT_CAPACITY), 2) AS OCCUPANCY_RATE
FROM REDBUS_ANALYTICS.SEMANTIC.VW_BOOKINGS
WHERE BOOKING_STATUS != 'CANCELLED'
GROUP BY BUS_TYPE
ORDER BY REVENUE DESC;

-- 9 , Customer Segmentation Analysis
SELECT 
    CUSTOMER_SEGMENT,
    SEGMENT_DESCRIPTION,
    COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMER_COUNT,
    COUNT(DISTINCT BOOKING_ID) AS BOOKINGS,
    SUM(NET_AMOUNT) AS REVENUE,
    AVG(NET_AMOUNT) AS AVG_SPEND_PER_BOOKING
FROM REDBUS_ANALYTICS.SEMANTIC.VW_BOOKINGS
WHERE BOOKING_STATUS != 'CANCELLED'
GROUP BY CUSTOMER_SEGMENT, SEGMENT_DESCRIPTION
ORDER BY REVENUE DESC;

-- 10 ,  Weekend vs Weekday Analysis
SELECT 
    JOURNEY_IS_WEEKEND,
    CASE WHEN JOURNEY_IS_WEEKEND = TRUE THEN 'Weekend' ELSE 'Weekday' END AS DAY_TYPE,
    COUNT(DISTINCT BOOKING_ID) AS BOOKINGS,
    SUM(PASSENGER_COUNT) AS PASSENGERS,
    SUM(NET_AMOUNT) AS REVENUE,
    AVG(NET_AMOUNT) AS AVG_FARE
FROM REDBUS_ANALYTICS.SEMANTIC.VW_BOOKINGS
WHERE BOOKING_STATUS != 'CANCELLED'
GROUP BY JOURNEY_IS_WEEKEND
ORDER BY JOURNEY_IS_WEEKEND;

-- now we are gonna start the Cortex RAG 
-- Create a Stage for Documents
CREATE OR REPLACE STAGE redbus_docs_stage;
LIST @redbus_docs_stage;

--  Create RAG Function in Snowflake
CREATE OR REPLACE TABLE REDBUS_ANALYTICS.DW.DOCS (
    DOC_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
    FILE_NAME VARCHAR(200),
    FILE_CONTENT VARCHAR(16777216),
    UPLOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Step 2: Create a Stage with Correct File Format
CREATE OR REPLACE STAGE redbus_docs_stage
FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = NONE RECORD_DELIMITER = '\\n' ESCAPE = NONE);


-- Step 3: Load Files Using COPY INTO
COPY INTO REDBUS_ANALYTICS.DW.DOCS (FILE_NAME, FILE_CONTENT)
FROM (
    SELECT 
        METADATA$FILENAME AS FILE_NAME,
        $1 AS FILE_CONTENT
    FROM @redbus_docs_stage
)
FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = NONE RECORD_DELIMITER = '\\n' ESCAPE = NONE);

SELECT * FROM REDBUS_ANALYTICS.DW.DOCS;

SHOW TABLES IN REDBUS_ANALYTICS.DW;

-- manually i have loaded all the documents 
INSERT INTO REDBUS_ANALYTICS.DW.DOCS (FILE_NAME, FILE_CONTENT) VALUES
('cancellation_policy.txt', 'REDBUS CANCELLATION POLICY

1. Standard Cancellation:
   - Free cancellation up to 24 hours before journey start time
   - 25% cancellation fee for cancellations between 12-24 hours before journey
   - 50% cancellation fee for cancellations between 6-12 hours before journey
   - No refund for cancellations within 6 hours of journey start time

2. Special Cancellation:
   - Premium customers (VIP) get free cancellation up to 12 hours before journey
   - Senior citizens (above 60 years) get 50% extra refund on all cancellations
   - Group bookings (5+ passengers) require 48 hours notice for free cancellation

3. Refund Process:
   - Refunds processed within 3-5 business days
   - Refund credited to original payment method
   - For cash payments, refund processed via bank transfer within 7 days

4. Exceptions:
   - Government-issued travel advisories: 100% refund
   - Natural disasters: 100% refund
   - Operator cancellation: 200% refund of ticket amount'),
   
('refund_rules.txt', 'REDBUS REFUND RULES

1. Refund Timeline:
   - Refunds processed within 24 hours of cancellation approval
   - Credit card refunds: 3-5 business days to reflect
   - UPI refunds: 1-2 business days to reflect
   - Bank transfer refunds: 5-7 business days to reflect

2. Refund Amount Calculation:
   - Total refund = Ticket amount - Cancellation fee
   - For partial journeys (used part of trip): Refund = 50% of unused portion

3. Refund Methods:
   - Original payment method gets priority refund
   - If original method unavailable, RedBus wallet credit offered
   - Wallet credit valid for 365 days from date of issue

4. Contact Information:
   - For refund queries: refunds@redbus.com
   - Support number: 1-800-REDBUS (1-800-733-287)'),

('operator_sop.txt', 'REDBUS OPERATOR STANDARD OPERATING PROCEDURES

1. Booking Confirmation:
   - Operators must confirm booking within 15 minutes of receipt
   - Seat allocation done automatically by system
   - Manual seat changes allowed only with customer consent

2. Bus Standards:
   - All buses must have GPS tracking
   - AC buses: Temperature maintained at 18-22°C
   - Non-AC buses: Windows must be in good condition

3. On-Time Performance:
   - Departure within 5 minutes of scheduled time: ON TIME
   - Departure between 5-30 minutes delayed: MINOR DELAY
   - Departure beyond 30 minutes delayed: MAJOR DELAY

4. Customer Service:
   - All queries responded within 2 hours
   - Complaints escalated within 24 hours
   - Resolution timeline: 48 hours for standard issues');

SELECT * FROM REDBUS_ANALYTICS.DW.DOCS;

-- Preview Content
SELECT 
    DOC_ID,
    FILE_NAME,
    LEFT(FILE_CONTENT, 100) AS PREVIEW
FROM REDBUS_ANALYTICS.DW.DOCS;

-- end of uploding the documents 

-- Create Cortex Search Service

WITH DOC_SEARCH AS (
    SELECT
        FILE_NAME,
        FILE_CONTENT
    FROM REDBUS_ANALYTICS.DW.DOCS
    WHERE LOWER(FILE_CONTENT) LIKE '%cancellation fee%'
)
SELECT * FROM DOC_SEARCH;


